#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_ICON                                100
#define IDM_GAMENEWGAME                         101
#define IDM_GAMEPAUSE                           102
#define IDM_GAMESTATISTICS                      103
#define IDM_GAMEHIGHSCORES                      104
#define IDM_GAMECOLORSMONOCHROME                110
#define IDM_GAMECOLORSBICOLOR                   111
#define IDM_GAMECOLORSMULTICOLOR                112
#define IDM_GAMEEXIT                            199
#define IDM_HELPABOUT                           200
#define IDD_HIGHSCORES                          1000
#define IDD_NEWHIGHSCORE                        1001
#define IDD_STATISTICS                          1002
#define IDC_HIGHSCORESNAME0                     40000
#define IDC_HIGHSCORESNAME1                     40001
#define IDC_HIGHSCORESNAME2                     40002
#define IDC_HIGHSCORESNAME3                     40003
#define IDC_HIGHSCORESNAME4                     40004
#define IDC_HIGHSCORESNAME5                     40005
#define IDC_HIGHSCORESNAME6                     40006
#define IDC_HIGHSCORESNAME7                     40007
#define IDC_HIGHSCORESNAME8                     40008
#define IDC_HIGHSCORESNAME9                     40009
#define IDC_HIGHSCORESSCORE0                    40010
#define IDC_HIGHSCORESSCORE1                    40011
#define IDC_HIGHSCORESSCORE2                    40012
#define IDC_HIGHSCORESSCORE3                    40013
#define IDC_HIGHSCORESSCORE4                    40014
#define IDC_HIGHSCORESSCORE5                    40015
#define IDC_HIGHSCORESSCORE6                    40016
#define IDC_HIGHSCORESSCORE7                    40017
#define IDC_HIGHSCORESSCORE8                    40018
#define IDC_HIGHSCORESSCORE9                    40019
#define IDC_HIGHSCORESLEVEL0                    40020
#define IDC_HIGHSCORESLEVEL1                    40021
#define IDC_HIGHSCORESLEVEL2                    40022
#define IDC_HIGHSCORESLEVEL3                    40023
#define IDC_HIGHSCORESLEVEL4                    40024
#define IDC_HIGHSCORESLEVEL5                    40025
#define IDC_HIGHSCORESLEVEL6                    40026
#define IDC_HIGHSCORESLEVEL7                    40027
#define IDC_HIGHSCORESLEVEL8                    40028
#define IDC_HIGHSCORESLEVEL9                    40029
#define IDC_NEWHIGHSCORENAME                    41000
#define IDC_STATISTICSBLOCKL                    42000
#define IDC_STATISTICSBLOCKI                    42001
#define IDC_STATISTICSBLOCKT                    42002
#define IDC_STATISTICSBLOCKS                    42003
#define IDC_STATISTICSBLOCKZ                    42004
#define IDC_STATISTICSBLOCKO                    42005
#define IDC_STATISTICSBLOCKJ                    42006
#define IDC_STATISTICSTOTAL                     42007
